### ISSUE TITLE
move or create a link to the README.md in the same dir as Chart.yaml

### ISSUE THREAD

**Issue by obeyler** [cloudfoundry-community/worlds-simplest-service-broker#21]
Helm chart need to have the README.md at same level than Chart.yaml as recommended by helm.

if you don't do  that,  tools like kubeapps or monocular won't be able to display information about your chart.
![image](https://user-images.githubusercontent.com/23224162/48513850-3eeb2300-e85d-11e8-9e07-0a1f9312dbde.png)

**Comment by drnic** [comment]
Thanks for letting me know. I'll sort it out.

**Comment by obeyler** [comment]
https://docs.helm.sh/developing_charts/#the-chart-file-structure

**Comment by drnic** [comment]
Reading it now. BTW, do you have some example helm charts that have your favourite/preferred README structure/style?
