### ISSUE TITLE
FEATURE: could you add an option to enable or not the user/password

### ISSUE THREAD

**Issue by obeyler** [cloudfoundry-community/worlds-simplest-service-broker#24]
I trying to expose the service of the world simpliest service broker with trafik ingress controller.
I need to have the service without basic auth because the ingress rule already have the auth mecanism. 
Is it possible to had this option inside the helm chart to have a way to disable the user/password check inside the pod as it s done by the ingress controller ?
Best regards

**Comment by drnic** [comment]
You’re welcome to submit a PR to get this working for you and I’ll try to
merge and cut release soon.

**Comment by drnic** [comment]
Quick look at this code, and brokerapi https://github.com/pivotal-cf/brokerapi/blob/master/api.go#L33-L38 - I'm not sure how far we'll get on this issue easily.

Can you configure your ingress controller to hardcode `user:pass` in the forwarded requests? Or perhaps include it in the forward base URL `http://user:pass@service-ip:port`?

Else, you might need to ask for this feature on brokerapi project?

**Comment by drnic** [comment]
I'll close this for now. I believe its a feature for https://github.com/pivotal-cf/brokerapi to implement first.
